# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Sep 15 18:31:49 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
