# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Aug 05 11:34:36 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-123154-Spike-Git
spec:
- template: Test_Template
  scheduledStartDate: 2025-08-04T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: xlrelease.Task
    - name: T2
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
